description = "General Rust agent"
resources = ["file://RUST.md"]
allowedTools = [ "@rustdocs", "@cargo" ] # also ["read", "knowledge", "web_search"] from default.toml
[mcpServers]
rustdocs = { type = "stdio" , command = "rust-docs-mcp", timeout = 1000 }
cargo = {  command = "cargo-mcp" , timeout = 1200  }

[toolsSettings]
[toolsSettings.shell]
allowedCommands = ["cargo .+" ] ## inherits allowedCommands from default.toml
deniedCommands = ["cargo publish .*"] ## inherits allowedCommands from default.toml
