"$schema" = "file://./schema.json"

[agents]
base = { skeleton = true }
dependabot = { inherits = ["aws-test"] }

[agents.aws-test]
inherits = ["base"]
[hooks]
[hooks.agentSpawn.whoami]
command = "aws get caller-identity"
